#
# Copyright © 2018-2019 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

cxf:
    path: /Service

server:
    port: 7070

valve:
    name: DoT
    configuration:
        token.path: ${TOKEN_PATH:https://api-demo.nam.drillops.slb.com/democore/BasicAuth/v1/token/}
        well.path: ${WELL_PATH:https://api-demo.nam.drillops.slb.com/democore/well/v2/witsml/wells/}
        well.gql.path: ${WELL_GQL_PATH:https://api-demo.nam.drillops.slb.com/democore/well/v2/graphql/}
        wellbore.path: ${WB_PATH:https://api-demo.nam.drillops.slb.com/democore/wellbore/v1/witsml/wellbores/}
        wellbore.gql.path: ${WB_GQL_PATH:https://api-demo.nam.drillops.slb.com/democore/wellbore/v1/graphql/}
        trajectory.path: ${TRAJ_PATH:https://api-demo.nam.drillops.slb.com/democore/trajectoryreader/v1/witsml/trajectories/}
        trajectory.gql.path: ${TRAJ_GQL_PATH:https://api-demo.nam.drillops.slb.com/democore/trajectoryreader/v1/graphql/}
        log.channelset.path: ${LOG_CHANNELSET_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channelSets}
        log.channel.path: ${LOG_CHANNEL_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels}
        log.channelset.uuid.path: ${LOG_CHANNELSET_UUID_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/identities}
        log.channels.path: ${LOG_CHANNELS_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/metadata}
        log.channels.data.path: ${LOG_CHANNELS_DATA_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/data}
        log.mnemonic.data.path: ${LOG_MNEMONIC_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/witsml/channels/:mnemonic}
        log.channel.depthData.path: ${LOG_DEPTHDATA_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/depthdata}
        log.channel.timeData.path: ${LOG_TIMEDATA_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/timedata}
        log.channel.depthBoundaryData.path: ${LOG_DEPTH_BOUNDARY_DATA_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/depthboundary}
        log.channel.timeBoundaryData.path: ${LOG_TIME_BOUNDARY_DATA_PATH:https://api-demo.nam.drillops.slb.com/democore/channelreader/v4/channels/timeboundary}
        fluids.report.path: ${FLUIDS_REPORT_PATH:https://api-demo.nam.drillops.slb.com/democore/fluidsreport/v1/witsml/fluidsReports}
        fluids.report.identities: ${FLUIDS_REPORT_IDENTITIES_PATH:https://api-demo.nam.drillops.slb.com/democore/fluidsreport/v1/identities}

wmls:
    version: 1.3.1.1,1.4.1.1
    compression: true

logging:
    config: ${LOGBACK_CONFIG_FILE:classpath:logback-spring.xml}

spring:
    config:
        import: classpath:base-messages.yml
    main:
        banner-mode: off
    devtools:
        add-properties: false